FROM node:16-alpine as build-step
WORKDIR /
ENV PATH /node_modules/.bin:$PATH
COPY package.json package-lock.json yarn.lock postcss.config.js tailwind.config.js ./
COPY ./src ./src
COPY ./public ./public
RUN yarn install
RUN yarn build

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step ./build /usr/share/nginx/html
COPY ./nginx.default.conf /etc/nginx/conf.d/default.conf